using Projeto_SEGUES.Models.User;

namespace Projeto_SEGUES.Services;

/// <summary>
/// Interface for the External Payment Integration Service.
/// Handles the communication with payment gateways (e.g., Stripe) to manage 
/// balance top-ups and transaction confirmations.
/// </summary>
public interface IPaymentService
{
    /// <summary>
    /// Creates a secure hosted checkout session for a balance top-up.
    /// </summary>
    /// <param name="user">The user entity requesting the top-up.</param>
    /// <param name="amount">The monetary value to be charged.</param>
    /// <param name="successUrl">The redirect URL for successful transactions.</param>
    /// <param name="cancelUrl">The redirect URL for cancelled or failed transactions.</param>
    /// <returns>A string containing the unique Checkout Session ID or Redirect URL.</returns>
    /// <remarks>
    /// This method offloads PCI compliance to the external provider by 
    /// redirecting the user to a secure payment page.
    /// </remarks>
    Task<string> CreateStripeSessionAsync(AppUser user, decimal amount, string successUrl, string cancelUrl);

    /// <summary>
    /// Processes and validates a successful payment after a callback from the provider.
    /// </summary>
    /// <param name="reference">The internal transaction reference generated by SEGUES.</param>
    /// <param name="sessionId">The external provider's unique session identifier.</param>
    /// <returns>A ServiceResult indicating if the balance was successfully credited.</returns>
    /// <remarks>
    /// This method must verify the transaction's authenticity before 
    /// updating the user's balance to prevent fraudulent top-ups.
    /// </remarks>
    Task<ServiceResult> ProcessPaymentSuccessAsync(string reference, string sessionId);
}