using Projeto_SEGUES.Extensions;
using System.ComponentModel.DataAnnotations;

namespace Projeto_SEGUES.Models.Audit.ViewModels;

/// <summary>
/// ViewModel used to display error information to the end-user in a graceful manner.
/// </summary>
/// <remarks>
/// This model contains the unique request identifier for support tracing and 
/// localized messages generated by the <see cref="AppErrorsExtensions"/>.
/// </remarks>
public class ErrorViewModel
{
    /// <summary>
    /// The unique identifier for the current HTTP request (Activity ID or Trace ID).
    /// </summary>
    /// <remarks>
    /// This ID is critical for developers to locate the specific stack trace in the 
    /// Serilog logs associated with a user's reported failure.
    /// </remarks>
    [Display(Name = "ID do Pedido")]
    public string? RequestId { get; set; }

    /// <summary>
    /// Logical flag used by the View to determine if the Request ID should be rendered.
    /// </summary>
    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    /// <summary>
    /// The user-friendly, localized description of what went wrong.
    /// </summary>
    [Required]
    [Display(Name = "Mensagem de Erro")]
    public required string ErrorMessage { get; set; }

    /// <summary>
    /// The numeric application error code (mapping to the AppErrors enum).
    /// </summary>
    [Required]
    [Display(Name = "Código de Erro")]
    public required int ErrorCode { get; set; }
}