using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Projeto_SEGUES.Models.User;
using System.ComponentModel.DataAnnotations;

namespace Projeto_SEGUES.Areas.Identity.Pages.Account
{
    /// <summary>
    /// Model responsible for the second stage of authentication (2FA - Two-Factor Authentication).
    /// </summary>
    /// <remarks>
    /// This page is invoked when the <see cref="LoginModel"/> detects that the user has 2FA active.
    /// It uses time-based tokens (Authenticator Apps) to validate the user's final identity.
    /// </remarks>
    public class LoginWith2FaModel : PageModel
    {
        private readonly SignInManager<AppUser> _signInManager;
        private readonly ILogger<LoginWith2FaModel> _logger;

        /// <summary>
        /// Initializes a new instance of <see cref="LoginWith2FaModel"/>.
        /// </summary>
        /// <param name="signInManager">Authentication manager to validate the 2FA token.</param>
        /// <param name="logger">Logging service to record login attempts and lockouts.</param>
        public LoginWith2FaModel(SignInManager<AppUser> signInManager, ILogger<LoginWith2FaModel> logger)
        {
            _signInManager = signInManager;
            _logger = logger;
        }

        /// <summary>
        /// Input model for the two-factor authentication code.
        /// </summary>
        [BindProperty]
        public required InputModel Input { get; set; }

        /// <summary>
        /// Maintains the state of the "Remember Me" option from the initial login page.
        /// </summary>
        public bool RememberMe { get; set; }

        /// <summary>
        /// URL for post-authentication redirection.
        /// </summary>
        public string? ReturnUrl { get; set; }

        /// <summary>
        /// Validation structure for the 2FA token.
        /// </summary>
        public class InputModel
        {
            /// <summary>
            /// 6-digit numeric code generated by the authenticator application.
            /// </summary>
            [Required(ErrorMessage = "O código é obrigatório.")]
            [StringLength(7, ErrorMessage = "O {0} deve ter entre {2} e {1} caracteres.", MinimumLength = 6)]
            [DataType(DataType.Text)]
            [Display(Name = "Código de autenticação")]
            public required string TwoFactorCode { get; init; }

            /// <summary>
            /// If true, the browser will be "remembered," not requesting 2FA on this device for a defined period.
            /// </summary>
            [Display(Name = "Lembrar este dispositivo")]
            public bool RememberMachine { get; init; }
        }

        /// <summary>
        /// Prepares the 2FA page, ensuring there is a user in the authentication flow.
        /// </summary>
        /// <param name="rememberMe">Session persistence state.</param>
        /// <param name="returnUrl">Destination after login.</param>
        /// <returns>The code entry page or redirection to Login if the context is lost.</returns>
        public async Task<IActionResult> OnGetAsync(bool rememberMe, string? returnUrl = null)
        {
            // Ensures the user has gone through the password challenge first
            var user = await _signInManager.GetTwoFactorAuthenticationUserAsync();
            if (user == null) return Challenge();

            ReturnUrl = returnUrl;
            RememberMe = rememberMe;
            return Page();
        }

        /// <summary>
        /// Processes and validates the 2FA code submitted by the user.
        /// </summary>
        /// <param name="rememberMe">Session persistence.</param>
        /// <param name="returnUrl">Destination after success.</param>
        /// <returns>Redirection to the local destination or lockout page in case of excessive failures.</returns>
        /// <remarks>
        /// The code is cleaned of spaces or hyphens before validation via <see cref="SignInManager{TUser}.TwoFactorAuthenticatorSignInAsync"/>.
        /// </remarks>
        public async Task<IActionResult> OnPostAsync(bool rememberMe, string? returnUrl = null)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            returnUrl ??= Url.Content("~/");

            var user = await _signInManager.GetTwoFactorAuthenticationUserAsync();
            if (user == null) return Challenge();

            // Normalization of the code (removes common formatting characters)
            var authenticatorCode = Input.TwoFactorCode.Replace(" ", "").Replace("-", "");

            var result = await _signInManager.TwoFactorAuthenticatorSignInAsync(authenticatorCode, rememberMe, Input.RememberMachine);

            if (result.Succeeded)
            {
                _logger.LogInformation("Utilizador com ID '{UserId}' fez login com 2FA.", user.Id);
                return LocalRedirect(returnUrl);
            }

            if (result.IsLockedOut)
            {
                _logger.LogWarning("Utilizador com ID '{UserId}' bloqueado.", user.Id);
                return RedirectToPage("./Lockout");
            }

            _logger.LogWarning("Código de autenticação inválido para o utilizador ID '{UserId}'.", user.Id);
            ModelState.AddModelError(string.Empty, "Código de autenticação inválido.");
            return Page();
        }
    }
}