using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using Projeto_SEGUES.Extensions;
using Projeto_SEGUES.Models.Enums;
using Projeto_SEGUES.Models.User;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace Projeto_SEGUES.Areas.Identity.Pages.Account
{
    /// <summary>
    /// Model responsible for resetting a user's password using a security token.
    /// </summary>
    /// <remarks>
    /// This page validates the token sent by email and allows the user to set a new credential,
    /// applying the same complexity rules as the initial registration.
    /// </remarks>
    public class ResetPasswordModel : PageModel
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly ILogger<ResetPasswordModel> _logger;

        /// <summary>
        /// Initializes a new instance of <see cref="ResetPasswordModel"/>.
        /// </summary>
        /// <param name="userManager">User manager to validate tokens and update passwords.</param>
        /// <param name="logger">Logger service for tracking errors and operations.</param>
        public ResetPasswordModel(UserManager<AppUser> userManager, ILogger<ResetPasswordModel> logger)
        {
            _userManager = userManager;
            _logger = logger;
        }

        /// <summary>
        /// Input model containing the data for the password reset.
        /// </summary>
        [BindProperty]
        public required InputModel Input { get; set; }

        /// <summary>
        /// Validation structure for the password reset fields.
        /// </summary>
        public class InputModel
        {
            /// <summary>User's email address.</summary>
            [Required]
            public required string Email { get; init; }

            /// <summary>New password with strong complexity validation.</summary>
            [Required(ErrorMessage = "A password é obrigatória.")]
            [StringLength(100, ErrorMessage = "A password deve ter pelo menos {2} e no máximo {1} caracteres.", MinimumLength = 12)]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\W_]).{12,}$",
                ErrorMessage = "A password deve ter pelo menos: 1 Minúscula, 1 Maiúscula, 1 Número e 1 Símbolo. E no mínimo 12 caracteres.")]
            public required string Password { get; init; }

            /// <summary>Confirmation of the new password.</summary>
            [DataType(DataType.Password)]
            [Display(Name = "Confirmar password")]
            [Compare("Password", ErrorMessage = "A password e a confirmação não coincidem.")]
            public required string ConfirmPassword { get; init; }

            /// <summary>Security code (token) generated by the system.</summary>
            [Required]
            public required string Code { get; init; }
        }

        /// <summary>
        /// Prepares the reset page by decoding the code received via URL.
        /// </summary>
        /// <param name="email">Email passed via QueryString.</param>
        /// <param name="code">Security token encoded in Base64.</param>
        /// <returns>The form page or an error if the token is missing.</returns>
        public IActionResult OnGet(string? email = null, string? code = null)
        {
            if (email == null || code == null)
            {
                _logger.LogAppError(AppErrors.InvalidToken, TableName.All, AppOperation.Other);
                TempData.SetSwalError(AppErrors.InvalidToken.GetViewErrorMessage());
                return RedirectToAction("Error", "Home", new { area = "", errorCode = AppErrors.InvalidToken });
            }
            Input = new InputModel
            {
                Email = email,
                Password = "",
                ConfirmPassword = "",
                Code = Encoding.UTF8.GetString(WebEncoders.Base64UrlDecode(code))
            };
            return Page();
        }

        /// <summary>
        /// Processes the submission of the new password.
        /// </summary>
        /// <returns>Redirect to the success page or reload with errors.</returns>
        /// <remarks>
        /// If the user has an account created by an administrator (not yet confirmed),
        /// success in this operation automatically activates the <see cref="AppUser.EmailConfirmed"/> property.
        /// </remarks>
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var user = await _userManager.FindByEmailAsync(Input.Email);
            if (user == null)
            {
                // For security, does not reveal that the user does not exist
                return RedirectToPage("./ResetPasswordConfirmation");
            }

            // Try to reset the password
            var result = await _userManager.ResetPasswordAsync(user, Input.Code, Input.Password);
            if (result.Succeeded)
            {
                if (user.EmailConfirmed) return RedirectToPage("./ResetPasswordConfirmation");

                // Confirm email for users created by admins
                user.EmailConfirmed = true;
                await _userManager.UpdateAsync(user);
                return RedirectToPage("./ResetPasswordConfirmation");
            }

            _logger.LogAppError(AppErrors.InvalidToken, TableName.All, AppOperation.Other);
            TempData.SetSwalError(AppErrors.InvalidToken.GetViewErrorMessage());
            return RedirectToAction("Error", "Home", new { area = "", errorCode = AppErrors.InvalidToken });
        }
    }
}