namespace Projeto_SEGUES.Areas.Report.ViewModels;

/// <summary>
/// Data Transfer Object (DTO) used for aggregating statistical data related to ticket consumption.
/// </summary>
/// <remarks>
/// This model provides high-level KPIs and chart-ready data specifically for the ticketing system, 
/// allowing administrators to track usage patterns and revenue generated from non-physical items.
/// </remarks>
public class ReportStatisticsTicketDto
{
    /// <summary>The total number of tickets that have been redeemed or used in the system.</summary>
    public int TotalUsedTickets { get; set; }

    /// <summary>The gross monetary value generated by the tickets.</summary>
    public decimal TotalRevenue { get; set; }

    /// <summary>The gross revenue formatted as a localized currency string.</summary>
    public string FormattedTotalRevenue => TotalRevenue.ToString("C");

    /// <summary>The average revenue generated per ticket (Total Revenue / Total Used).</summary>
    public decimal AverageRevenue { get; set; }

    /// <summary>The average ticket revenue formatted as a localized currency string.</summary>
    public string FormattedAverageRevenue => AverageRevenue.ToString("C");

    /// <summary>The total count of unique users who have purchased or used tickets.</summary>
    public int NumberOfBuyers { get; set; }

    /// <summary>List of general trend data (e.g., tickets used over time) for chart rendering.</summary>
    public List<ChartDataDto> Chart { get; set; } = [];

    /// <summary>Breakdown of ticket usage grouped by specific categories.</summary>
    public List<CategoryDataDto> ByCategory { get; set; } = [];
}