//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_SEGUES.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Projeto_SEGUES.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        public static string DatabaseConnectionError {
            get {
                return ResourceManager.GetString("DatabaseConnectionError", resourceCulture);
            }
        }
        
        public static string DatabaseQueryError {
            get {
                return ResourceManager.GetString("DatabaseQueryError", resourceCulture);
            }
        }
        
        public static string DataNotFoundError {
            get {
                return ResourceManager.GetString("DataNotFoundError", resourceCulture);
            }
        }
        
        public static string ConcurrencyError {
            get {
                return ResourceManager.GetString("ConcurrencyError", resourceCulture);
            }
        }
        
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        public static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        public static string UserAlreadyRegistered {
            get {
                return ResourceManager.GetString("UserAlreadyRegistered", resourceCulture);
            }
        }
        
        public static string InvalidOperation {
            get {
                return ResourceManager.GetString("InvalidOperation", resourceCulture);
            }
        }
        
        public static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        public static string InsufficientFunds {
            get {
                return ResourceManager.GetString("InsufficientFunds", resourceCulture);
            }
        }
        
        public static string EmailSenderError {
            get {
                return ResourceManager.GetString("EmailSenderError", resourceCulture);
            }
        }
        
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        public static string InvalidQuantity {
            get {
                return ResourceManager.GetString("InvalidQuantity", resourceCulture);
            }
        }
        
        public static string PricingNotAvailable {
            get {
                return ResourceManager.GetString("PricingNotAvailable", resourceCulture);
            }
        }
        
        public static string TicketNotFound {
            get {
                return ResourceManager.GetString("TicketNotFound", resourceCulture);
            }
        }
        
        public static string TicketAlreadyUsed {
            get {
                return ResourceManager.GetString("TicketAlreadyUsed", resourceCulture);
            }
        }
        
        public static string TicketExpired {
            get {
                return ResourceManager.GetString("TicketExpired", resourceCulture);
            }
        }
        
        public static string TicketNotAvailable {
            get {
                return ResourceManager.GetString("TicketNotAvailable", resourceCulture);
            }
        }
        
        public static string RecipientNotFound {
            get {
                return ResourceManager.GetString("RecipientNotFound", resourceCulture);
            }
        }
        
        public static string TransferToSelf {
            get {
                return ResourceManager.GetString("TransferToSelf", resourceCulture);
            }
        }
        
        public static string CategoryMismatch {
            get {
                return ResourceManager.GetString("CategoryMismatch", resourceCulture);
            }
        }
        
        public static string TicketsNotOwned {
            get {
                return ResourceManager.GetString("TicketsNotOwned", resourceCulture);
            }
        }
        
        public static string ProductCategoryNotFound {
            get {
                return ResourceManager.GetString("ProductCategoryNotFound", resourceCulture);
            }
        }
        
        public static string ProductAlreadyExists {
            get {
                return ResourceManager.GetString("ProductAlreadyExists", resourceCulture);
            }
        }
        
        public static string ProductCreateError {
            get {
                return ResourceManager.GetString("ProductCreateError", resourceCulture);
            }
        }
        
        public static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        public static string ProductEditError {
            get {
                return ResourceManager.GetString("ProductEditError", resourceCulture);
            }
        }
        
        public static string ProductDeleteError {
            get {
                return ResourceManager.GetString("ProductDeleteError", resourceCulture);
            }
        }
        
        public static string CartEmpty {
            get {
                return ResourceManager.GetString("CartEmpty", resourceCulture);
            }
        }
        
        public static string SchedulePast {
            get {
                return ResourceManager.GetString("SchedulePast", resourceCulture);
            }
        }
        
        public static string InvalidPickupTime {
            get {
                return ResourceManager.GetString("InvalidPickupTime", resourceCulture);
            }
        }
        
        public static string BarClosed {
            get {
                return ResourceManager.GetString("BarClosed", resourceCulture);
            }
        }
        
        public static string InsufficientStock {
            get {
                return ResourceManager.GetString("InsufficientStock", resourceCulture);
            }
        }
        
        public static string OrderProcessingError {
            get {
                return ResourceManager.GetString("OrderProcessingError", resourceCulture);
            }
        }
        
        public static string OrderCannotCancel {
            get {
                return ResourceManager.GetString("OrderCannotCancel", resourceCulture);
            }
        }
        
        public static string OrderCancelError {
            get {
                return ResourceManager.GetString("OrderCancelError", resourceCulture);
            }
        }
        
        public static string InvalidStatusTransition {
            get {
                return ResourceManager.GetString("InvalidStatusTransition", resourceCulture);
            }
        }
        
        public static string UseCancelFunction {
            get {
                return ResourceManager.GetString("UseCancelFunction", resourceCulture);
            }
        }
        
        public static string DatabaseUpdateError {
            get {
                return ResourceManager.GetString("DatabaseUpdateError", resourceCulture);
            }
        }
        
        public static string RedemptionCodeRequired {
            get {
                return ResourceManager.GetString("RedemptionCodeRequired", resourceCulture);
            }
        }
        
        public static string InvalidRedemptionCode {
            get {
                return ResourceManager.GetString("InvalidRedemptionCode", resourceCulture);
            }
        }
        
        public static string CodeExpired {
            get {
                return ResourceManager.GetString("CodeExpired", resourceCulture);
            }
        }
        
        public static string IncorrectCode {
            get {
                return ResourceManager.GetString("IncorrectCode", resourceCulture);
            }
        }
        
        public static string ResendEmailError {
            get {
                return ResourceManager.GetString("ResendEmailError", resourceCulture);
            }
        }
        
        public static string EmailAlreadyRegistered {
            get {
                return ResourceManager.GetString("EmailAlreadyRegistered", resourceCulture);
            }
        }
        
        public static string SendActivationEmailError {
            get {
                return ResourceManager.GetString("SendActivationEmailError", resourceCulture);
            }
        }
        
        public static string InvalidTimeFormat {
            get {
                return ResourceManager.GetString("InvalidTimeFormat", resourceCulture);
            }
        }
        
        public static string NoItemsSelected {
            get {
                return ResourceManager.GetString("NoItemsSelected", resourceCulture);
            }
        }
        
        public static string RecipientEmailRequired {
            get {
                return ResourceManager.GetString("RecipientEmailRequired", resourceCulture);
            }
        }
        
        public static string OrderCreationError {
            get {
                return ResourceManager.GetString("OrderCreationError", resourceCulture);
            }
        }
    }
}
